[FLINK-36648] Bump Flink version to Flink 2.0-preview1
apache/flink-connector-kafka pull request #140
Opened 2024-12-04 09:46 UTC by lvyanquan

Bump Flink version to Flink 2.0-preview1.
This is required as flink-example module and flink-e2e-to-e2e-tests need to use Kafka connector for testing, and some other  project like Apache Paimon also rely on Kafka connector in test.

This pr is based on https://github.com/apache/flink-connector-kafka/pull/139 to remove many deprecated classes.
And as there is a bug in SinkTestSuiteBase/SourceTestSuiteBase in Flink 2.0-preview1 as https://issues.apache.org/jira/browse/FLINK-36845 described, temporarily annotated relevant test as this will need to wait for a new release of Flink(Or we can directly cover these classes).

2024-12-04 09:47 UTC, lvyanquan commented
> Bump Flink version to Flink 2.0-preview1. This is required as [flink-example](https://issues.apache.org/jira/browse/FLINK-example) module and [flink-e2e-to-e2e-tests](https://issues.apache.org/jira/browse/FLINK-e2e-to-e2e-tests) need to use Kafka connector for testing, and some other project like Apache Paimon also rely on Kafka connector in test.
> 
> This pr is based on #139 to remove many deprecated classes. And as there is a bug in SinkTestSuiteBase/SourceTestSuiteBase in Flink 2.0-preview1 as https://issues.apache.org/jira/browse/FLINK-36845 described, temporarily commented relevant tests out as this will need to wait for a new release of Flink(Or we can directly cover these classes).

2024-12-09 09:18 UTC, leonardBang commented
@PatrickRen Would you like to review this PR when you have time?

2025-01-08 18:04 UTC, PatrickRen requested changes
@lvyanquan Thanks for the awesome contribution! I found more classes that can be removed.

I simply searched keyword `deprecated` in the repo, and there are still some appearances. Could you check them all?

Also I see a lot of empty files under `flink-connector-kafka/archunit-violations`. I think we should remove them as well.

2025-01-08 18:04 UTC, PatrickRen commented on flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaShortRetentionTestBase.java
> -    public void runAutoOffsetResetTest() throws Exception {
This file is not needed anymore. No one is inheriting it.

2025-01-09 12:01 UTC, lvyanquan commented
> Also I see a lot of empty files under flink-connector-kafka/archunit-violations. I think we should remove them as well.

Remove some empty files, and remain some files which were referenced in [stored.rules](https://github.com/apache/flink-connector-kafka/blob/main/flink-connector-kafka/archunit-violations/stored.rules).

2025-02-05 08:48 UTC, lvyanquan commented
Hi, @PatrickRen can you help to review again and help to complete this PR？

2025-02-18 07:09 UTC, lvyanquan commented
Hi @PatrickRen. I have made adjustments based on your previous suggestion. Can you help confirm if there are any other suggestions?  
Since this PR is likely to conflict with other PRs, it will be troublesome to rebase multiple times in the future. and @AHeise,  I've addressed the comments in https://github.com/apache/flink-connector-kafka/pull/139 too, do you have time to help review the remaining parts？

2025-02-19 12:54 UTC, gyfora commented on .github/workflows/push_pr.yml
> +        jdk: [ '11, 17, 21' ]
Since Flink 2.0 is built on Java 17 can we simply build this there as well? Then we can remove Java 11 from the CI matrix

2025-03-25 09:58 UTC, prshnt commented on .github/workflows/push_pr.yml
> +        jdk: [ '11, 17, 21' ]
Also Flink is out of the preview version now right.

2025-03-25 11:26 UTC, lvyanquan commented on .github/workflows/push_pr.yml
> +        jdk: [ '11, 17, 21' ]
Done.

2025-03-25 11:27 UTC, lvyanquan commented
Rebase and rearrange to make commit message more clearly.

2025-03-27 01:28 UTC, lvyanquan commented
Hi, @PatrickRen @leonardBang @gyfora  could you take a look at this as Flink 2.0.0 was released recently.

2025-03-27 01:34 UTC, mlegore commented
I hope this can be released soon! Would love to move to 2.0 for our project

2025-03-27 04:15 UTC, leonardBang approved these changes
Thanks @lvyanquan for the great work, LGTM

2025-03-27 07:12 UTC, rmetzger commented on flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/dynamic/source/DynamicKafkaSourceITTest.java
>  }
Why is this test commented out. I fear we are losing test coverage by this

2025-03-27 07:26 UTC, lvyanquan commented on flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/dynamic/source/DynamicKafkaSourceITTest.java
>  }
Thanks for pointing out this, and I've removed the comment.

This was added because there is a bug in SinkTestSuiteBase/SourceTestSuiteBase in Flink 2.0-preview1 as https://issues.apache.org/jira/browse/FLINK-36845 described, and I commented out some related cases to pass CI, but this operation was not need now.

2025-03-27 08:22 UTC, prshnt commented on .github/workflows/weekly.yml
> +          flink: 2.1-SNAPSHOT,
what do you think about using the main branch with the stable release of Flink and not the snapshot?

2025-03-27 08:43 UTC, lvyanquan commented on .github/workflows/weekly.yml
> +          flink: 2.1-SNAPSHOT,
I tend to add both snapshot and stable versions to ensure compatibility, and this runs weekly with minimal resource overhead.

2025-03-27 09:46 UTC, prshnt approved these changes

2025-03-27 12:46 UTC, prshnt commented
Thanks @lvyanquan for the PR and taking care of this.

2025-03-28 03:13 UTC, leonardBang commented
CI passed, merging...

2025-03-28 03:25 UTC, merged

2025-04-07 16:32 UTC, FranMorilloAWS commented
When is this releasing?